### ISSUE TITLE
Runnable Jar File?

### ISSUE THREAD

**Issue by Aruvelut-123** [thecodeofnotch/rd-131655#7]
I'm wondering can u make it can compile to a runnable jar file so that i can run it with other launchers or something

**Comment by LabyStudio** [comment]
Done https://github.com/thecodeofnotch/rd-131655/releases/tag/build

**Comment by Aruvelut-123** [comment]
How u build that cause other versions that you guys makes are not runnable jars too i wondering to make some

**Comment by LabyStudio** [comment]
Using the build task of gradle. If you want to include the libraries directly you might want to use a gradle plugin like shadow

**Comment by Aruvelut-123** [comment]
oh thanks
